# Generated by Django 4.0.5 on 2022-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('pub_timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='event/images')),
            ],
        ),
    ]
