# Generated by Django 4.0.5 on 2022-06-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
