# Generated by Django 4.0.5 on 2022-06-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
